### ISSUE TITLE
The music control no working

### ISSUE THREAD

**Issue by jerfeson** [swdotcom/swdc-intellij-music-time#17]
**Describe the bug**
The music control no working in phpstorm 2020.1, i can't play music, or playlist,  only list

**ISSUE TYPE**
- Bug Report

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Plugin version: 1.1.2

This process is very bureaucratic, and I think in give  up  reporting the issue

**Comment by brettmstevens7** [comment]
@jerfeson we'll look at this today

**Comment by brettmstevens7** [comment]
@jerfeson this is fixed.
