### ISSUE TITLE
Fails to connect (or fails to fetch playlists)

### ISSUE THREAD

**Issue by rekkih** [swdotcom/swdc-intellij-music-time#18]
**Describe the bug**
```paste below
When setting up the plugin and authorizing Spotify, a popup appears, however the plugin view is still stuck on "Connect Spotify", even after waiting.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Install the plugin via Marketplace
2. Click on "Connect Spotify"
3. Scroll down, click on "Allow" on Spotify's OAuth Page
4. Click "OK" on the new popup in Webstorm

**Expected behavior**
```paste below
Music Time shows recommendations, etc.
```

**ACTUAL RESULTS**

```paste below
Music Time does not recognize fully that Spotify was connected, and tells me to Connect Spotify over and over.
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1909
 - Plugin version 2.0.2

**Additional context**
```paste below

```

**Comment by xavluiz** [comment]
Thank you for the bug information. We have identified the issue and updating our app. It will be available momentarily. We apologize for the inconvenience.

**Comment by xavluiz** [comment]
Spotify connection is available again. thank you again for the update.
