### ISSUE TITLE
Music Time for other streaming service like Youtube Music

### ISSUE THREAD

**Issue by Deewens** [swdotcom/swdc-intellij-music-time#40]
##### SUMMARY

```paste below
Music Time for other streaming service like Youtube Music
```

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

```paste below
I don't like Spotify and I am a Youtube Music user, it would be good to have a plugin compatible with Youtube Music as well!
```

**Comment by mmclead** [comment]
That would be great to add, but they don't provide a usable API to control playback or connect to a particular account.  If they create an API we'd be able to support it.
